In [28]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [29]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [30]:
df.shape

(569, 33)

In [31]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [32]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### train test split

In [33]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### scaling

In [34]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [35]:
X_train

array([[ 1.06714829, -2.03725513,  1.23611461, ...,  2.2589165 ,
         2.72799946,  1.90880767],
       [-0.71485169, -0.25160597, -0.6458541 , ...,  0.40204934,
        -0.37446057,  0.48010642],
       [ 1.66581076,  2.05371289,  1.57666905, ...,  0.72002659,
        -0.51511822, -0.95568381],
       ...,
       [ 1.76372285,  0.4992824 ,  1.6293739 , ...,  0.44554622,
        -1.0489779 , -0.68848395],
       [-0.11339173,  0.68929379, -0.06812782, ...,  0.78752176,
         0.29685999,  0.51446069],
       [-0.35957069, -1.40998863, -0.42246661, ..., -0.9169563 ,
        -0.93549276, -0.80408879]])

In [36]:
y_train

0      M
469    B
565    M
516    M
283    M
      ..
544    B
105    M
237    M
196    M
287    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [37]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [38]:
y_train

array([1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,

### Numpy arrays to PyTorch tensors

In [39]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [40]:
X_train_tensor.shape

torch.Size([455, 30])

In [41]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [65]:
X_test_tensor.shape[1]

30

In [267]:
# help(torch.normal)

In [272]:
l = torch.normal(mean=0,std=1,size= (1,2), requires_grad=True, dtype=torch.float64)
l

TypeError: normal() got an unexpected keyword argument 'Random_State'

In [243]:
w=l

In [250]:
w

tensor([[2.4337, 1.7725]], dtype=torch.float64, requires_grad=True)

In [273]:
torch.random.seed=55

In [159]:
# help(torch.normal)

Help on built-in function normal in module torch:

normal(...)
    normal(mean, std, *, generator=None, out=None) -> Tensor

    Returns a tensor of random numbers drawn from separate normal distributions
    whose mean and standard deviation are given.

    The :attr:`mean` is a tensor with the mean of
    each output element's normal distribution

    The :attr:`std` is a tensor with the standard deviation of
    each output element's normal distribution

    The shapes of :attr:`mean` and :attr:`std` don't need to match, but the
    total number of elements in each tensor need to be the same.

    .. note:: When the shapes do not match, the shape of :attr:`mean`
              is used as the shape for the returned output tensor

    .. note:: When :attr:`std` is a CUDA tensor, this function synchronizes
              its device with the CPU.

    Args:
        mean (Tensor): the tensor of per-element means
        std (Tensor): the tensor of per-element standard deviations

    Keywo

In [293]:
class MySimpleNN():

  def __init__(self, X):

    self.weights1 = torch.normal(0,1, size=(X.shape[1], 16), dtype=torch.float64, requires_grad=True)
    self.weights2 = torch.normal(0,1, size=(16, 8), dtype = torch.float64, requires_grad = True)
    self.weights3 = torch.normal(0,1, size=(8, 1), dtype= torch.float64, requires_grad = True)
    # self.weights4 = torch.rand(4,1, dtype= torch.float64, requires_grad = True)
    self.bias1 = torch.zeros(16, dtype=torch.float64, requires_grad=True)
    self.bias2 = torch.zeros(8, dtype=torch.float64, requires_grad=True)
    self.bias3 = torch.zeros(1, dtype=torch.float64, requires_grad=True)
    # self.bias4 = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    x = torch.matmul(X, self.weights1) + self.bias1
    x = torch.tanh(x)
    y = torch.matmul(x, self.weights2) + self.bias2
    y = torch.tanh(y)
    z = torch.matmul(y, self.weights3) + self.bias3
    # f = torch.tanh(z)
    # f = torch.matmul(z, self.weights4) + self.bias4
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

### Important Parameters

In [294]:
learning_rate = 0.05
epochs = 1000

### Training Pipeline

In [295]:
# create model
model = MySimpleNN(X_train_tensor)
min_loss=float('inf')
# define loop
c=0
for epoch in range(epochs):
    
    # forward pass
    y_pred = model.forward(X_train_tensor)
    
    # loss calculate
    loss = model.loss_function(y_pred, y_train_tensor)
    
    # backward pass
    loss.backward()
    
    # parameters update
    with torch.no_grad():
        model.weights1 -= learning_rate * model.weights1.grad
        model.bias1 -= learning_rate * model.bias1.grad
        model.weights2 -= learning_rate * model.weights2.grad
        model.bias2 -= learning_rate * model.bias2.grad
        model.weights3 -= learning_rate * model.weights3.grad
        model.bias3 -= learning_rate * model.bias3.grad
        # model.weights4 -= learning_rate * model.weights4.grad
        # model.bias4 -= learning_rate * model.bias4.grad
    
    # zero gradients
    model.weights1.grad.zero_()
    model.bias1.grad.zero_()
    model.weights2.grad.zero_()
    model.bias2.grad.zero_()
    model.weights3.grad.zero_()
    model.bias3.grad.zero_()
    # model.weights4.grad.zero_()
    # model.bias4.grad.zero_()
    # print loss in each epoch
    # if loss<1.5:
    #     l=loss
    #     learning_rate/=5
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')
    
    if min_loss-loss.item()>0.001:
        c=0
        min_loss=loss
        mw1= model.weights1
        mb1= model.bias1
        mw2= model.weights2
        mb2= model.bias2
        mw3= model.weights3
        mb3= model.bias3
    elif c>5:
        model.weights1= mw1
        model.bias1= mb1
        model.weights2=mw2
        model.bias2=mb2
        model.weights3=mw3
        model.bias3=mb3
        break
    else:
        c+=1

Epoch: 1, Loss: 1.4233703949265597
Epoch: 2, Loss: 1.387110410920686
Epoch: 3, Loss: 1.3528372600329106
Epoch: 4, Loss: 1.3209171549070307
Epoch: 5, Loss: 1.2915426620230213
Epoch: 6, Loss: 1.2646349029510673
Epoch: 7, Loss: 1.239930191282827
Epoch: 8, Loss: 1.2171505276594445
Epoch: 9, Loss: 1.1961218180057835
Epoch: 10, Loss: 1.1767474159314062
Epoch: 11, Loss: 1.1588941655020624
Epoch: 12, Loss: 1.1423641862936285
Epoch: 13, Loss: 1.1269583738722222
Epoch: 14, Loss: 1.1125196544814009
Epoch: 15, Loss: 1.0989362097015112
Epoch: 16, Loss: 1.0861308065495288
Epoch: 17, Loss: 1.0740491241954635
Epoch: 18, Loss: 1.0626496940534402
Epoch: 19, Loss: 1.0518960978822078
Epoch: 20, Loss: 1.0417520037512438
Epoch: 21, Loss: 1.0321790739071726
Epoch: 22, Loss: 1.0231370048619484
Epoch: 23, Loss: 1.0145846436436394
Epoch: 24, Loss: 1.0064813427864578
Epoch: 25, Loss: 0.998788120321645
Epoch: 26, Loss: 0.9914684975562703
Epoch: 27, Loss: 0.9844890326610941
Epoch: 28, Loss: 0.9778196032146492
Epoc

### Evaluation

In [296]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.6491228342056274


In [297]:
pip install torchinfo

Note: you may need to restart the kernel to use updated packages.


In [299]:
from torchinfo import summary

In [301]:
# summary(model,input_size= X_train_tensor.shape)