In [5]:
import torch
print(torch.__version__)

2.5.1+cpu


In [6]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


## Creating a Tensor

In [7]:
# using empty
a = torch.empty(2,3)

In [10]:
a.shape

torch.Size([2, 3])

In [11]:
# check type
type(a)

torch.Tensor

In [12]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
# using rand
torch.rand(2,3)

tensor([[0.6670, 0.0081, 0.9105],
        [0.9871, 0.1406, 0.5388]])

In [21]:
help(torch.random)

Help on module torch.random in torch:

NAME
    torch.random - # mypy: allow-untyped-defs

FUNCTIONS
    fork_rng(devices=None, enabled=True, _caller='fork_rng', _devices_kw='devices', device_type='cuda') -> Generator
        Forks the RNG, so that when you return, the RNG is reset
        to the state that it was previously in.

        Args:
            devices (iterable of Device IDs): devices for which to fork
                the RNG. CPU RNG state is always forked. By default, :meth:`fork_rng` operates
                on all devices, but will emit a warning if your machine has a lot
                of devices, since this function will run very slowly in that case.
                If you explicitly specify devices, this warning will be suppressed
            enabled (bool): if ``False``, the RNG is not forked.  This is a convenience
                argument for easily disabling the context manager without having
                to delete it and unindent your Python code under it.
 

In [30]:
# use of seed
c=torch.random.seed()
torch.rand(2,3)

tensor([[0.0948, 0.4509, 0.9975],
        [0.5904, 0.0789, 0.7344]])

In [31]:
# manual_seed
torch.manual_seed(c)
torch.rand(2,3)

tensor([[0.0948, 0.4509, 0.9975],
        [0.5904, 0.0789, 0.7344]])

In [32]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [33]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [34]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [35]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [40]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [41]:
x.shape

torch.Size([2, 3])

In [42]:
torch.empty_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [43]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [44]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [45]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [46]:
# find data type
x.dtype

torch.int64

In [47]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [48]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [49]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [50]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [54]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

### 2. Element wise operation

In [55]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [56]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [57]:
c = torch.tensor([1, -2, 3, -4])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [58]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [59]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [60]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [61]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [62]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [65]:
torch.randint(0,10,(3,3),dtype=torch.float32)

tensor([[9., 9., 7.],
        [5., 9., 8.],
        [9., 7., 9.]])

In [63]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [67]:
# sum
print(torch.sum(e))
# sum along columns
print(torch.sum(e, dim=0))
# sum along rows
print(torch.sum(e, dim=1))

tensor(24.)
tensor([ 8.,  0., 16.])
tensor([15.,  9.])


In [68]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([4., 0., 8.])

In [69]:
# median
torch.median(e)

tensor(0.)

In [70]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [71]:
# product
torch.prod(e)

tensor(0.)

In [72]:
# standard deviation
torch.std(e)

tensor(4.4272)

In [73]:
# variance
torch.var(e)

tensor(19.6000)

In [74]:
# argmax
torch.argmax(e)

tensor(5)

In [75]:
# argmin
torch.argmin(e)

tensor(1)

### 4. Matrix operations

In [76]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[2, 6, 7],
        [7, 8, 3]])
tensor([[6, 1],
        [5, 5],
        [0, 4]])


In [77]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[42, 60],
        [82, 59]])

In [78]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# transpose
torch.transpose(f, 0, 1)

tensor([[3, 7],
        [7, 9],
        [8, 9]])

In [79]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[3., 8., 8.],
        [3., 3., 5.],
        [0., 6., 4.]])

In [80]:
# determinant
torch.det(h)

tensor(-6.)

In [81]:
# inverse
torch.inverse(h)

tensor([[ 3.0000, -2.6667, -2.6667],
        [ 2.0000, -2.0000, -1.5000],
        [-3.0000,  3.0000,  2.5000]])

### 5. Comparison operations

In [82]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[0, 8, 4],
        [7, 2, 3]])
tensor([[8, 5, 6],
        [2, 9, 5]])


In [83]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

### 6. Special functions

In [84]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 4., 2.],
        [7., 1., 1.]])

In [85]:
# log
torch.log(k)

tensor([[  -inf, 1.3863, 0.6931],
        [1.9459, 0.0000, 0.0000]])

In [86]:
# exp
torch.exp(k)

tensor([[1.0000e+00, 5.4598e+01, 7.3891e+00],
        [1.0966e+03, 2.7183e+00, 2.7183e+00]])

In [87]:
# sqrt
torch.sqrt(k)

tensor([[0.0000, 2.0000, 1.4142],
        [2.6458, 1.0000, 1.0000]])

In [88]:
# sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.9820, 0.8808],
        [0.9991, 0.7311, 0.7311]])

In [89]:
# softmax
torch.softmax(k, dim=0)

tensor([[9.1105e-04, 9.5257e-01, 7.3106e-01],
        [9.9909e-01, 4.7426e-02, 2.6894e-01]])

In [90]:
# relu
torch.relu(k)

tensor([[0., 4., 2.],
        [7., 1., 1.]])

## Inplace Operations

In [91]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])
tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])


In [92]:
m.add_(n)

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [93]:
m

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [94]:
n

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [95]:
torch.relu(m)

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [96]:
m.relu_()

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [98]:
# relu: Use this when you need to retain the original tensor for other computations.
# relu_: Use this when memory efficiency is crucial, and the input tensor does not need to be preserved.

In [97]:
m

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

## Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.5153, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.5153, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
a[0][0] = 0

In [ ]:
a

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
b

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
id(a)

134838567488544

In [ ]:
id(b)

134838567488544

In [ ]:
b = a.clone()

In [ ]:
a

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
b

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
a[0][0] = 10

In [ ]:
a

tensor([[10.0000,  0.9985,  0.6783],
        [ 0.2776,  0.6227,  0.2982]])

In [ ]:
b

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
id(a)

134838567488544

In [ ]:
id(b)

134838569581552